# 1-Numpy

## 1- For Arrays


In [1]:
# import
import numpy as np

In [2]:
a= np.array([1,2,3,4,5,6])
print("1-D Array: ",a)

1-D Array:  [1 2 3 4 5 6]


In [3]:
b= np.array([[1,2,3],[4,5,6]])
print("Multi-D:",b)
print(b.shape)
c= np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
d=np.array([[1,2,3],[4,5,6],[7,8,9],[10,22,44]])
print("--------------")
print(d)

print(d.shape)

Multi-D: [[1 2 3]
 [4 5 6]]
(2, 3)
--------------
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 22 44]]
(4, 3)


In [4]:
#Array Full of Zeros
c=np.zeros([2,2])
print(c)

[[0. 0.]
 [0. 0.]]


In [5]:
#Array Full of ones
d=np.ones([2,2])
print(d)

[[1. 1.]
 [1. 1.]]


In [6]:
#Array With Random Initial Values
e=np.empty([3,3])
print(e)

[[0.000e+000 0.000e+000 0.000e+000]
 [0.000e+000 0.000e+000 6.087e-321]
 [0.000e+000 0.000e+000 0.000e+000]]


In [7]:
#Array With Ones In The Diagonal and Zeros o.w

print(np.eye(5))

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [8]:
e= np.asarray([1,2,3,4,5,6]) #One-D
print(e)

[1 2 3 4 5 6]


In [9]:
#The Difference Between np.array and np.asarray
a=np.array([1,2],dtype=np.float32)

print(np.array(a,dtype=np.float32) is a)
print(np.array(a,dtype=np.float64) is a)

print(np.asarray(a,dtype=np.float32) is a)
print(np.asarray(a,dtype=np.float64) is a)

False
False
True
False


In [10]:
A = np.matrix(np.ones((3,3)))
print(A)
print("----------------------")
np.array(A)[2]=2
print(A)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
----------------------
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [11]:
A = np.matrix(np.ones((3,3)))
print(A)
print("----------------------")
np.asarray(A)[2]=2
print(A)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
----------------------
[[1. 1. 1.]
 [1. 1. 1.]
 [2. 2. 2.]]


In [12]:
#Sequence of Numbers 
f=np.arange(10,20,2)  #arange(start,end,step)
print(f)

[10 12 14 16 18]


In [13]:
g=np.linspace(0,99,10) 
print(g)

[ 0. 11. 22. 33. 44. 55. 66. 77. 88. 99.]


## 2-Important Attributies

In [14]:
a=np.array([[1,2],[3,4],[5,6]])
print(a.shape)
b=np.array([[[2],[2]],[[3],[4]],[[4],[5]]])
print(b.shape)

(3, 2)
(3, 2, 1)


In [15]:
print(a.size)
# print(b.size)

6


In [16]:
print(a.ndim)
print(b.ndim)

2
3


In [17]:
a.dtype

dtype('int32')

In [18]:
b=np.array([1.1,.5])
b.dtype

dtype('float64')

## 3-Indexing & Slicing

In [19]:
a=np.array([[[1,2],[3,4]],[[5,6],[7,8]]])  #Indexing
b=a[1][1][1]
print("a:",a)
print("b:",b)

a: [[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
b: 8


In [20]:
a=np.arange(10)        #Slicing   [0,1,2,3,4,5,6,7,8,9]
print(a[2:8:2])
print(a[2:8])
print(a[2])
print(a[2:])

[2 4 6]
[2 3 4 5 6 7]
2
[2 3 4 5 6 7 8 9]


## 4-Change The Shape of an array

In [21]:
a=np.arange(6)         
print(a,"-->",a.shape)
a.reshape(2,3)
print(a,"-->",a.shape)
print("----------------")
b=a.reshape(2,3)
print(b,"-->",b.shape)

[0 1 2 3 4 5] --> (6,)
[0 1 2 3 4 5] --> (6,)
----------------
[[0 1 2]
 [3 4 5]] --> (2, 3)


## 5. Broadcasting

In [22]:
a=np.array([1,2,3,4])
b=np.array([1,2,3,4])
c=a*b
print(c)

# a=[1,2,3,4]
# b=[1,2,3,4]
# c=a*3
# print(c)

[ 1  4  9 16]


In [23]:
# a=np.array([1,2,3,4])
# b=np.array([1,2,3])
# c=a*b
# print(c)


In [24]:
a=np.array([[1,2,3],[4,5,6],[7,8,9]])
b=np.array([1,2,3])
print("shape of a:",a.shape)
print("shape of b:",b.shape)
c=np.array([b,b,b])
print("[b,b,b]:",c)
d=a+c
print("broadcasing:\n",d)


shape of a: (3, 3)
shape of b: (3,)
[b,b,b]: [[1 2 3]
 [1 2 3]
 [1 2 3]]
broadcasing:
 [[ 2  4  6]
 [ 5  7  9]
 [ 8 10 12]]


In [25]:
a=np.array([[1,2,3],[4,5,6],[7,8,9]])
b=np.array([1,2,3])
c=a+b
print(c)

[[ 2  4  6]
 [ 5  7  9]
 [ 8 10 12]]


## 6-Numpy Common Functions

In [26]:
a=np.array([[1,2,3],[4,5,6],[7,8,9]]) #flat Function
print(a)
print(a.flat[:])
# print(a.shape)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[1 2 3 4 5 6 7 8 9]


In [27]:
#Transpose 
a=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(a.shape)
print(a)
print("-------------")
print(np.transpose(a))

(3, 3)
[[1 2 3]
 [4 5 6]
 [7 8 9]]
-------------
[[1 4 7]
 [2 5 8]
 [3 6 9]]


In [28]:
#Concate 
a=np.arange(6).reshape(2,3)
b=np.arange(7,13).reshape(2,3)
print(a)
print("---------------")
print(b)

[[0 1 2]
 [3 4 5]]
---------------
[[ 7  8  9]
 [10 11 12]]


In [29]:
print(np.concatenate((a,b),axis=0))
np.concatenate((a,b),axis=0).shape

[[ 0  1  2]
 [ 3  4  5]
 [ 7  8  9]
 [10 11 12]]


(4, 3)

In [30]:
print(np.concatenate((a,b),axis=1)) 
np.concatenate((a,b),axis=1).shape

[[ 0  1  2  7  8  9]
 [ 3  4  5 10 11 12]]


(2, 6)

In [31]:
#Stack Function 
a=np.arange(6).reshape(2,3)
b=np.arange(7,13).reshape(2,3)
c=np.stack((a,b),0)
d=np.stack((a,b),1)
print(a)
print(b)
print("c:\n",c)
print("-------------")
print("d:\n",d)
print(np.stack((a,b),0).shape)
print(np.stack((a,b),1).shape)

[[0 1 2]
 [3 4 5]]
[[ 7  8  9]
 [10 11 12]]
c:
 [[[ 0  1  2]
  [ 3  4  5]]

 [[ 7  8  9]
  [10 11 12]]]
-------------
d:
 [[[ 0  1  2]
  [ 7  8  9]]

 [[ 3  4  5]
  [10 11 12]]]
(2, 2, 3)
(2, 2, 3)


In [32]:
#append
a=np.array([[1,2,3],[4,5,6]])
b=np.append(a,[[7,8,9]],axis=0)
print(a)
print("------------")
print(b)

[[1 2 3]
 [4 5 6]]
------------
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [33]:
c=np.append(a,[[7,8,9]])
print(c)

[1 2 3 4 5 6 7 8 9]


In [34]:
#insert
a=np.arange(6).reshape(2,3)
print("a: ",a)
b=np.insert(a,2,[7,8],axis=1)    
print("b: ",b)
c=np.insert(a,2,[7,8])   
print("c: ",c)

a:  [[0 1 2]
 [3 4 5]]
b:  [[0 1 7 2]
 [3 4 8 5]]
c:  [0 1 7 8 2 3 4 5]


In [35]:
a=np.arange(6).reshape(2,3)  # 0,2,3,4,5
b=np.delete(a,1,axis=1)
c=np.delete(a,1)  
print("a: ",a)
print("b: ",b)
print("c: ",c)

a:  [[0 1 2]
 [3 4 5]]
b:  [[0 2]
 [3 5]]
c:  [0 2 3 4 5]


## 7- Matrix

In [36]:
import numpy.matlib

In [37]:
mat_a=np.matlib.zeros((2,2))   #Matrix Full of Zeros
print(mat_a)

[[0. 0.]
 [0. 0.]]


In [38]:
mat_b=np.matlib.ones((2,2))   #Matrix Full of Ones
print(mat_b)

[[1. 1.]
 [1. 1.]]


In [39]:
c=np.matlib.eye((3))  #Matrix With Ones in Diagonal
print(c)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [40]:
#Transfer Between Matrix and Array by np.mat()

#Transfer Array to Matrix
a=np.array([[1,2],[3,4]])
b=np.mat(a)
print("a: ",a)
print(type(a))
print("b: ",b)
print(type(b))


a:  [[1 2]
 [3 4]]
<class 'numpy.ndarray'>
b:  [[1 2]
 [3 4]]
<class 'numpy.matrix'>


In [41]:
#Transfer Matrix to Array  by getA()
a=np.mat([[1,2,3],[4,5,6]])
print("a: ",a)
print(type(a))
b=a.getA()
print("b: ",b)
print(type(b))

a:  [[1 2 3]
 [4 5 6]]
<class 'numpy.matrix'>
b:  [[1 2 3]
 [4 5 6]]
<class 'numpy.ndarray'>


In [42]:
#Create A matrix with random Values by rand()
a=np.matlib.rand(3,3)
print(a)

[[0.64952872 0.40676305 0.57022777]
 [0.35771744 0.99782273 0.47999641]
 [0.16778636 0.38132276 0.82057934]]


In [43]:
#Matrix Operations 

#1-Matrix Multiplication
a=np.array([[1,0],[0,1]])
b=np.array([[1,1],[2,2]])
print("a:\n",a,"\n","b:\n",b)

print("Multiply by dot()\n",np.dot(a,b))  
print("Multiply by @\n",a@b)
print("Multiply by np.multiply()\n",np.multiply(a,b))
print("Multiply by *\n",a*b)


a:
 [[1 0]
 [0 1]] 
 b:
 [[1 1]
 [2 2]]
Multiply by dot()
 [[1 1]
 [2 2]]
Multiply by @
 [[1 1]
 [2 2]]
Multiply by np.multiply()
 [[1 0]
 [0 2]]
Multiply by *
 [[1 0]
 [0 2]]


In [44]:
a=np.array([1,2,3])
b=np.mat(a)
c=np.matrix(a)
d=np.asmatrix(a)
print("a= ",a ,a.shape)
print("b= ",b ,b.shape)
print("c= ",c ,c.shape)
print("d= ",d ,d.shape)

a=  [1 2 3] (3,)
b=  [[1 2 3]] (1, 3)
c=  [[1 2 3]] (1, 3)
d=  [[1 2 3]] (1, 3)


In [45]:
#Inverse Matrix
a=np.matrix([[2,0,0],
           [0,1,0],
           [0,0,2]])
b=a.I
print(a)
print(b)

[[2 0 0]
 [0 1 0]
 [0 0 2]]
[[0.5 0.  0. ]
 [0.  1.  0. ]
 [0.  0.  0.5]]


In [46]:
np.linalg.inv(b)

matrix([[2., 0., 0.],
        [0., 1., 0.],
        [0., 0., 2.]])

In [47]:
#Det. of a matrix

a=np.matrix([[1,2],[3,4]])
b=np.linalg.det(a)
print("Matrix a: \n",a)
print("Det. of Matrix a: \n",b)

Matrix a: 
 [[1 2]
 [3 4]]
Det. of Matrix a: 
 -2.0000000000000004


In [48]:
#Sum Function
a=np.array([[1,2],
           [3,4]])
b=a.sum(axis=0)   #Sum by Col.s
c=a.sum(axis=1)   #Sum by Rows

print("a:\n",a)
print("b:\n",b)
print("c:\n",c)


a:
 [[1 2]
 [3 4]]
b:
 [4 6]
c:
 [3 7]


In [49]:
#Min and Max Functions
d=a.min()
e=a.max()
print("Min of a:",d)
print("\nMax of a:",e)

Min of a: 1

Max of a: 4


## Random Sampling

In [50]:
r1=np.random.rand(2,2)
r2=np.random.randn(2,2)
r3=np.random.randint(0,5)

print("r1: ",r1)
print("\nr2: ",r2)
print("\nr3: ",r3)

r1:  [[0.38943983 0.17929981]
 [0.0982321  0.49225462]]

r2:  [[-0.7658067  -0.62248638]
 [-0.63055024 -1.89716986]]

r3:  2


In [51]:
r3=np.random.choice([1,2,3,4,5],(2,2))
print(r3)

[[3 4]
 [3 4]]


In [52]:
#Permutation
a=np.array([1,2,3,4,5])
print("Before Shuffle:",a)
np.random.shuffle(a)
print(a)
b=np.random.permutation(a)
print(b)


Before Shuffle: [1 2 3 4 5]
[5 1 4 2 3]
[5 4 2 1 3]


In [53]:
#Distributions

r1=np.random.normal(0,0.1,5)
r2=np.random.uniform(0,5,2)
print(r1)
print(r2)

[ 0.10134757  0.13740602  0.13666401 -0.21500043 -0.10958911]
[2.77738789 3.95293621]


## Common Mathematical Functions

In [54]:
#Sin & Cos
a=np.array([0,30,45,60,90])
b=np.sin(a*np.pi/180)
c=np.cos(a*np.pi/180)
print(a)
print(b)
print(c)

[ 0 30 45 60 90]
[0.         0.5        0.70710678 0.8660254  1.        ]
[1.00000000e+00 8.66025404e-01 7.07106781e-01 5.00000000e-01
 6.12323400e-17]


In [55]:
#Rounding
a=np.array([1.0,1.4,2.0,2.55])
b=np.around(a)
c=np.around(a,decimals=1)
print(b)
print(c)
d=np.floor(a)
print(d)
e=np.ceil(a)
print(e)

[1. 1. 2. 3.]
[1.  1.4 2.  2.6]
[1. 1. 2. 2.]
[1. 2. 2. 3.]


In [56]:
#Arithmatic Operations
a=np.array([1,2,3,4])
b=np.array([4,3,2,1])
c=np.add(a,b)
d=np.subtract(a,b)
print("a+b:",c)
print("a-b:",d)
e=np.multiply(a,b)
print("a*b:",e)
f=np.divide(a,b)
print("a/b:",f)
g=np.mod(a,b)
print("a mod b:",g)
h=np.power(a,b)
print("a^b:",h)

a+b: [5 5 5 5]
a-b: [-3 -1  1  3]
a*b: [4 6 6 4]
a/b: [0.25       0.66666667 1.5        4.        ]
a mod b: [1 2 1 0]
a^b: [1 8 9 4]


In [57]:
#Statistical Functions
a=np.array([[6,7,2],[0,1,5]])        # 6,7,2,0,1,5 ---> #0,1,2,5,6,7
b=np.amin(a,axis=0)    #min from each Col
print(b)
c=np.amax(a,axis=1)    #max from each row
print(c)
d=np.median(a)
print("Median:",d)
e=np.mean(a)
print("Mean:",e)

[0 1 2]
[7 5]
Median: 3.5
Mean: 3.5


In [58]:
#Sort Function
a=np.array([[3,5,1],[2,8,7]])   #[3 5 1 ]
b=np.sort(a)                    #[2 8 7 ]
print(b)
c=np.sort(a,axis=0)
print(c)

[[1 3 5]
 [2 7 8]]
[[2 5 1]
 [3 8 7]]


## Generator

In [59]:
import collections as c
print(isinstance([],c.Iterable))
print(isinstance('abc',c.Iterable))
print(isinstance(100,c.Iterable))


True
True
False


<ipython-input-59-867bc1cdbd39>:2: DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated since Python 3.3, and in 3.9 it will stop working
  print(isinstance([],c.Iterable))


In [60]:
l=[1,2,3,4,5]
print(type(l))
it=iter(l)
print(type(it))

<class 'list'>
<class 'list_iterator'>


In [61]:
next(it)

1

In [62]:
next(it)

2

In [66]:
#fib Function 
def fib(n):
    c= 0
    num1,num2= 0,1
    while (c < n):
        num=num1
        num1,num2= num2,num1+num2
        c=c+1
        yield num
    yield "done"
g=fib(5)    
for x in g:
    print(x)

0
1
1
2
3
done
<generator object fib at 0x000001C43D4EBAC0>


In [64]:
g=[x*2 for x in range(5)]
for x in g:
    print(x)


0
2
4
6
8


## Decorator

In [68]:
def decorate(func):
    def decorated():
        print("i got decorated")
        func()
    return decorated

@decorate
def plain():
    print("iam plain")
    
plain()


i got decorated
iam plain
